import RelationAlgebra.Kleene.Basic
import RelationAlgebra.Kleene.Quantale
import RelationAlgebra.Kleene.Complete
import RelationAlgebra.KAT.Defs
import RelationAlgebra.KAT.Basic
import RelationAlgebra.KAT.Hoare
import RelationAlgebra.Converse
import RelationAlgebra.Residuated
import RelationAlgebra.Allegory
import RelationAlgebra.Vectors
import RelationAlgebra.Typed
import RelationAlgebra.Models.Rel
import RelationAlgebra.Models.Bool
import RelationAlgebra.Models.Trace
import RelationAlgebra.Models.Matrix
import RelationAlgebra.Models.SetoidRel
import RelationAlgebra.Models.FinRel
import RelationAlgebra.Decide.Term
import RelationAlgebra.Decide.Antimirov
import RelationAlgebra.Decide.Tactic
import RelationAlgebra.Decide.GuardedString
import RelationAlgebra.Decide.KATSound
import RelationAlgebra.Decide.KATTactic
import RelationAlgebra.Examples.Basic
import RelationAlgebra.Examples.Decide
