import RelationAlgebra.Decide.KATSound
import Mathlib.Order.Hom.BoundedLattice
import Mathlib.Algebra.Order.BigOperators.Group.List
import Mathlib.Algebra.Order.Group.Nat

/-!
# Boolean expressions modulo semantic equality

`KAT.FreeTest` is the Boolean algebra freely generated by the test variables `ℕ`.
Its elements are Boolean expressions modulo agreement on **all** finite atoms. There is
no fixed bound on variable indices. `FreeTest.lift` extends a valuation to a Boolean
algebra homomorphism, and `FreeTest.lift_unique` proves uniqueness.

This supplies the test component of the typed expression quotient, following the free
syntax construction in Damien Pous's `relation-algebra/theories/gregex.v`.
-/

namespace KAT
namespace BTerm

/-- Boolean semantic equality, tested at every finite atom. -/
def SemEq (b c : BTerm) : Prop := ∀ α : Atom, α.sat b = α.sat c

/-- Agreement on atoms implies agreement in every Boolean algebra. -/
theorem SemEq.eval_eq {b c : BTerm} (h : b.SemEq c)
    {T : Type*} [BooleanAlgebra T] (τ : ℕ → T) : b.eval τ = c.eval τ := by
  let k := (b.tvars ++ c.tvars).sum + 1
  have hb : ∀ i ∈ b.tvars, i < k := fun i hi ↦
    Nat.lt_succ_of_le (List.le_sum_of_mem (List.mem_append_left _ hi))
  have hc : ∀ i ∈ c.tvars, i < k := fun i hi ↦
    Nat.lt_succ_of_le (List.le_sum_of_mem (List.mem_append_right _ hi))
  rw [eval_eq_lsup τ k b hb, eval_eq_lsup τ k c hc]
  congr 1
  funext α
  rw [h α]

/-- The setoid used by the free Boolean algebra. -/
def semanticSetoid : Setoid BTerm where
  r := SemEq
  iseqv := ⟨fun _ _ ↦ rfl, fun h α ↦ (h α).symm, fun h g α ↦ (h α).trans (g α)⟩

end BTerm

/-- Boolean expressions quotiented by agreement on all finite atoms. -/
def FreeTest := Quotient BTerm.semanticSetoid

namespace FreeTest

/-- The equivalence class of a Boolean expression. -/
def ofTerm (b : BTerm) : FreeTest := Quotient.mk _ b

@[simp] theorem ofTerm_eq_iff {b c : BTerm} : ofTerm b = ofTerm c ↔ b.SemEq c :=
  Quotient.eq

/-- The satisfying atoms of a Boolean expression class. -/
def atoms : FreeTest → Set Atom := Quotient.lift (fun b ↦ {α | α.sat b = true})
  (fun _ _ h ↦ Set.ext fun α ↦ by simp only [Set.mem_setOf_eq, h α])

@[simp] theorem atoms_ofTerm (b : BTerm) : (ofTerm b).atoms = {α | α.sat b = true} := rfl

theorem atoms_injective : Function.Injective atoms := by
  intro b c
  refine Quotient.inductionOn₂ b c fun b c h ↦ Quotient.sound ?_
  intro α
  have hh := Set.ext_iff.mp h α
  exact Bool.eq_iff_iff.mpr hh

private def unary (f : BTerm → BTerm)
    (hf : ∀ b c, b.SemEq c → (f b).SemEq (f c)) : FreeTest → FreeTest :=
  Quotient.map f hf

private def binary (f : BTerm → BTerm → BTerm)
    (hf : ∀ b b' c c', b.SemEq b' → c.SemEq c' → (f b c).SemEq (f b' c')) :
    FreeTest → FreeTest → FreeTest := Quotient.map₂ f (fun {_ _} hb {_ _} hc ↦ hf _ _ _ _ hb hc)

instance : Top FreeTest := ⟨ofTerm .top⟩
instance : Bot FreeTest := ⟨ofTerm .bot⟩
instance : Max FreeTest := ⟨binary .or (by intros b b' c c' hb hc α; simp [Atom.sat, hb α, hc α])⟩
instance : Min FreeTest := ⟨binary .and (by intros b b' c c' hb hc α; simp [Atom.sat, hb α, hc α])⟩
instance : Compl FreeTest := ⟨unary .not (by intros b c h α; simp [Atom.sat, h α])⟩
instance : SDiff FreeTest := ⟨fun b c ↦ b ⊓ cᶜ⟩
instance : HImp FreeTest := ⟨fun b c ↦ c ⊔ bᶜ⟩
instance : LE FreeTest := ⟨fun b c ↦ b.atoms ⊆ c.atoms⟩
instance : LT FreeTest := ⟨fun b c ↦ b.atoms < c.atoms⟩

@[simp] theorem atoms_top : atoms ⊤ = ⊤ := by ext α; simp [atoms, Top.top, ofTerm, Atom.sat]
@[simp] theorem atoms_bot : atoms ⊥ = ⊥ := by ext α; simp [atoms, Bot.bot, ofTerm, Atom.sat]
@[simp] theorem atoms_sup (b c : FreeTest) : atoms (b ⊔ c) = atoms b ⊔ atoms c := by
  refine Quotient.inductionOn₂ b c fun b c ↦ ?_
  ext α
  change (α.sat (.or b c) = true) ↔ α ∈ ({α | α.sat b = true} ∪ {α | α.sat c = true})
  simp [Atom.sat]
@[simp] theorem atoms_inf (b c : FreeTest) : atoms (b ⊓ c) = atoms b ⊓ atoms c := by
  refine Quotient.inductionOn₂ b c fun b c ↦ ?_
  ext α
  change (α.sat (.and b c) = true) ↔ α ∈ ({α | α.sat b = true} ∩ {α | α.sat c = true})
  simp [Atom.sat]
@[simp] theorem atoms_compl (b : FreeTest) : atoms bᶜ = (atoms b)ᶜ := by
  refine Quotient.inductionOn b fun b ↦ ?_
  ext α
  simp [atoms, Atom.sat, Compl.compl, unary]

instance : BooleanAlgebra FreeTest := atoms_injective.booleanAlgebra atoms
  Iff.rfl Iff.rfl atoms_sup atoms_inf atoms_top atoms_bot atoms_compl
  (fun b c ↦ by change atoms (b ⊓ cᶜ) = _; rw [atoms_inf, atoms_compl, sdiff_eq])
  (fun b c ↦ by change atoms (c ⊔ bᶜ) = _; rw [atoms_sup, atoms_compl, himp_eq])

@[simp] theorem ofTerm_top : ofTerm .top = ⊤ := rfl
@[simp] theorem ofTerm_bot : ofTerm .bot = ⊥ := rfl
@[simp] theorem ofTerm_or (b c : BTerm) : ofTerm (.or b c) = ofTerm b ⊔ ofTerm c := rfl
@[simp] theorem ofTerm_and (b c : BTerm) : ofTerm (.and b c) = ofTerm b ⊓ ofTerm c := rfl
@[simp] theorem ofTerm_not (b : BTerm) : ofTerm (.not b) = (ofTerm b)ᶜ := rfl

/-- A free test generator. -/
def var (i : ℕ) : FreeTest := ofTerm (.tvar i)

/-- Every class is the evaluation of a Boolean expression in the generators. -/
@[simp] theorem eval_var (b : BTerm) : b.eval var = ofTerm b := by
  induction b <;> simp_all [BTerm.eval, var]

/-- Extend a valuation to a Boolean algebra homomorphism. -/
def lift {T : Type*} [BooleanAlgebra T] (τ : ℕ → T) : BoundedLatticeHom FreeTest T where
  toFun := Quotient.lift (BTerm.eval τ) (fun _ _ h ↦ h.eval_eq τ)
  map_sup' b c := Quotient.inductionOn₂ b c fun _ _ ↦ rfl
  map_inf' b c := Quotient.inductionOn₂ b c fun _ _ ↦ rfl
  map_top' := rfl
  map_bot' := rfl

@[simp] theorem lift_ofTerm {T : Type*} [BooleanAlgebra T] (τ : ℕ → T) (b : BTerm) :
    lift τ (ofTerm b) = b.eval τ := rfl

@[simp] theorem lift_var {T : Type*} [BooleanAlgebra T] (τ : ℕ → T) (i : ℕ) :
    lift τ (var i) = τ i := rfl

/-- A Boolean homomorphism is determined by its values on the test generators. -/
theorem lift_unique {T : Type*} [BooleanAlgebra T] (τ : ℕ → T)
    (f : BoundedLatticeHom FreeTest T) (h : ∀ i, f (var i) = τ i) : f = lift τ := by
  apply BoundedLatticeHom.ext
  intro b
  refine Quotient.inductionOn b fun b ↦ ?_
  change f (ofTerm b) = b.eval τ
  induction b with
  | top => exact map_top f
  | bot => exact map_bot f
  | tvar i => exact h i
  | and b c hb hc => simp only [ofTerm_and, map_inf, hb, hc, BTerm.eval]
  | or b c hb hc => simp only [ofTerm_or, map_sup, hb, hc, BTerm.eval]
  | not b hb => simp only [ofTerm_not, map_compl', hb, BTerm.eval]

end FreeTest
end KAT
